### ISSUE TITLE
Add Google PaLM

### ISSUE THREAD

**Issue by orenelbaum** [abacaj/awesome-transformers#4]
Google PaLM is possibly the strongest LLM currently, a bit weird that it's not on the list

**Comment by abacaj** [comment]
I don’t think there’s any code available though?

**Comment by orenelbaum** [comment]
Yeah you're right. I found this though https://github.com/lucidrains/PaLM-rlhf-pytorch
Seems pretty interesting.

**Comment by abacaj** [comment]
Closing for now, that would fall more under frameworks and no weights available
